
pool:
  name: Azure Pipelines
  demands:
  - msbuild
  - visualstudio

steps:

- task: UseDotNet@2
  inputs:
    version: '6.0.8'
- task: VSBuild@1
  displayName: 'Build solution **\*.sln'

- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    versioningScheme: byBuildNumber

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    publishVstsFeed: '1e90aa70-2283-458a-8bb9-8eaad5d43b8b/244ad4da-6cd0-47e3-9a18-1bfdbb01fc35'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
